# Site settings
title: "Nitish's Resume"
description: "A resume demonstrating my skills and their application in real-world projects"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nitish Kumar"
resume_title:                   "Software Development Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "imnitishh@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced Software Engineer with a solid foundation in Java development and a proven track record of delivering innovative solutions. I have 4 years of experience working in collaborative teams to build scalable, high-performance applications. My current role at Clearwater Analytics involves designing and implementing a client management portal using industry-standard technologies. I am proficient in core Java concepts, as well as popular frameworks like SpringBoot for efficient development. Additionally, I have a strong understanding of testing methodologies (Mockito) and build tools (Maven). My experience with AWS services allows me to leverage cloud-based infrastructure for scalable and reliable solutions. I am seeking a software engineer(Java) role to leverage my expertise and contribute to your organization's goals.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/touristintech/"
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/touristintech/"
  # resume_instagram_url:         ""
  #resume_website_url:           ""
  resume_medium_url:            "https://touristintech.medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
